In [49]:
!pip install sklearn.utils

In [50]:
import pandas as pd
import numpy as np
import sklearn
from sklearn import linear_model
import sklearn.utils
from sklearn.utils import shuffle

Since I am using Google Colab I have to upload files from my local drive

In [51]:
from google.colab import files
uploaded = files.upload()

Saving student-mat.csv to student-mat (2).csv


Read the input File

In [52]:
import io
df2 = pd.read_csv(io.BytesIO(uploaded['student-mat.csv']),sep=";")
print(df2.head())

  school sex  age address famsize Pstatus  Medu  Fedu     Mjob      Fjob  ...  \
0     GP   F   18       U     GT3       A     4     4  at_home   teacher  ...   
1     GP   F   17       U     GT3       T     1     1  at_home     other  ...   
2     GP   F   15       U     LE3       T     1     1  at_home     other  ...   
3     GP   F   15       U     GT3       T     4     2   health  services  ...   
4     GP   F   16       U     GT3       T     3     3    other     other  ...   

  famrel freetime  goout  Dalc  Walc health absences  G1  G2  G3  
0      4        3      4     1     1      3        6   5   6   6  
1      5        3      3     1     1      3        4   5   5   6  
2      4        3      2     2     3      3       10   7   8  10  
3      3        2      2     1     1      5        2  15  14  15  
4      4        3      2     1     2      5        4   6  10  10  

[5 rows x 33 columns]


Extracting out the necessary columns required

In [53]:
df2 = df2[["G1","G2","G3","studytime","failures","absences"]]
print(df2.head())

   G1  G2  G3  studytime  failures  absences
0   5   6   6          2         0         6
1   5   5   6          2         0         4
2   7   8  10          2         3        10
3  15  14  15          3         0         2
4   6  10  10          2         0         4


Selecting the field that is going to be predicted

In [54]:
predict = "G3"

This is the crucial step. From the given input we are going to remove the field which is going to be predicted. These set of fields which will help us to predict the G3 value is known as attributes

In [55]:
X = np.array(df2.drop([predict],1))
print(X)

[[ 5  6  2  0  6]
 [ 5  5  2  0  4]
 [ 7  8  2  3 10]
 ...
 [10  8  1  3  3]
 [11 12  1  0  0]
 [ 8  9  1  0  5]]


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: FutureWarning: In a future version of pandas all arguments of DataFrame.drop except for the argument 'labels' will be keyword-only
  """Entry point for launching an IPython kernel.


Likewise, extract out the prediction field alone G3 which will now be known as labels

In [56]:
Y = np.array(df2[predict])
print(Y)

[ 6  6 10 15 10 15 11  6 19 15  9 12 14 11 16 14 14 10  5 10 15 15 16 12
  8  8 11 15 11 11 12 17 16 12 15  6 18 15 11 13 11 12 18 11  9  6 11 20
 14  7 13 13 10 11 13 10 15 15  9 16 11 11  9  9 10 15 12  6  8 16 15 10
  5 14 11 10 10 11 10  5 12 11  6 15 10  8  6 14 10  7  8 18  6 10 14 10
 15 10 14  8  5 17 14  6 18 11  8 18 13 16 19 10 13 19  9 16 14 13  8 13
 15 15 13 13  8 12 11  9  0 18  0  0 12 11  0  0  0  0 12 15  0  9 11 13
  0 11  0 11  0 10  0 14 10  0 12  8 13 10 15 12  0  7  0 10  7 12 10 16
  0 14  0 16 10  0  9  9 11  6  9 11  8 12 17  8 12 11 11 15  9 10 13  9
  8 10 14 15 16 10 18 10 16 10 10  6 11  9  7 13 10  7  8 13 14  8 10 15
  4  8  8 10  6  0 17 13 14  7 15 12  9 12 14 11  9 13  6 10 13 12 11  0
 12 12  0 12  0 18 13  8  5 15  8 10  8  8 12  8 13 11 14  0 18  8 12  9
  0 17 10 11 10  0  9 14 11 14 10 12  9  9  8 10  8 10 12 10 11 11 19 12
 14 15 11 15 13 18 14 11  0  8 14 16 11 10 14 18 13 12 18  8 12 10  0 13
 11 11 13 11  0  9 10 11 13  9 11 15 15 11 16 10  9

Split the data into four components
x_train = Training our model with the attributes
y_train = contains the actual G3 values against which our model will be trained and checked for prediction accuracy
x_test = portion of the attribute data used for testing our model
y_train = portion of the actual label values against which our model will be tested and checked for prediction accuracy
Test size 0.1 indicates that 90 percent of the data will be used to train and 10 percent of the data will be used for testing

In [57]:
x_train,x_test,y_train,y_test = sklearn.model_selection.train_test_split(X,Y,test_size=0.1)

Create object linear regression

In [58]:
linear = linear_model.LinearRegression()

Fit the training data

In [59]:
linear.fit(x_train,y_train)

LinearRegression()

Now predict the accuracy for testing data

In [60]:
acc = linear.score(x_test,y_test)
print(acc)

0.865924227327806


Co efficients and intercept values
Since I am using 5 attributes there will be 5 co efficients

In [61]:
print("Coefficients (m) : \n", linear.coef_)
print("Intercept : \n", linear.intercept_)

Coefficients (m) : 
 [ 0.16490723  0.98276365 -0.21827343 -0.21059259  0.03785832]
Intercept : 
 -1.631630005955449


Now the comparison between predicted and actual values for testing data
First value is the predicted data
Second array is the input attributes
Third value is the actual data

In [62]:
predictions = linear.predict(x_test)
for p in range(len(predictions)):
  print(predictions[p],x_test[p],y_test[p])

8.56372757622261 [9 9 2 0 8] 9
9.319341273346678 [ 9 10  2  0  2] 9
14.368922068628011 [14 14  1  0  4] 14
19.22001641757315 [17 18  2  0 21] 18
14.781247383933875 [11 15  1  0  2] 15
16.4993565856943 [15 16  1  0  4] 15
11.917549614567493 [11 12  2  0 10] 13
6.97678353264266 [ 9  7  2  0 18] 6
6.34869989316419 [8 7 1 0 0] 6
5.801515284040382 [8 7 2 3 8] 8
6.1304264618290745 [8 7 2 0 0] 8
16.370273731854653 [16 16  2  0  2] 17
10.525544082268594 [13 10  2  1 22] 11
8.283211423719335 [10  9  3  0  2] 9
14.119632877609034 [16 14  4  0  6] 15
9.898656119820643 [12 10  3  0 10] 12
4.318366421931967 [6 5 1 0 7] 6
5.680405670995192 [7 7 4 0 4] 6
9.312017552880409 [ 9  9  1  0 22] 9
8.425768205722639 [10  9  2  0  0] 9
12.373380142490781 [10 13  2  1  6] 13
8.913810170360312 [ 7 10  2  0  0] 11
12.412271295049324 [14 12  2  0 10] 11
3.9865180165991347 [6 5 2 0 4] 6
6.791056492923827 [6 8 1 1 0] 8
12.15817349072658 [12 12  2  0 12] 11
15.311793437403333 [16 15  2  0  0] 15
19.111038855078768 [